name: Candidate Monitor

on:
  schedule:
    - cron: "0 14,20,2 * * *"  # 9am, 3pm, 9pm EST -> 14:00, 20:00, 02:00 UTC

  workflow_dispatch:       # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore candidate cache
        uses: actions/cache@v3
        id: cache
        with:
          path: discord_bot/candidate_cache
          key: candidate-cache-${{ github.run_id }}
          restore-keys: |
            candidate-cache-

      - name: Run candidate monitor
        run: python discord_tracker.py

      - name: Save updated candidate cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: discord_bot/candidate_cache
          key: candidate-cache-${{ github.run_id }}
